### ISSUE TITLE
Blind Oracle fails to install

### ISSUE THREAD

**Issue by Alex71btc** [valerio-vaccaro/umbrel-test-repo#1]
Hey, thx for developing this cool app!
However if i try to install via the umbrel community app store it fails to install, but hangs on status "installing" forever...
![image](https://github.com/valerio-vaccaro/umbrel-test-repo/assets/105175715/db0cc08c-055c-4292-aab1-50ebeb317988)

**Comment by valerio-vaccaro** [comment]
Looks like there is another app using the same port, I will migrate web port from 8081 to 8095.
